#!/bin/bash 
set -eu
cat <<EOF
Usage: 
    $0 [job ID] [TYPE (md / smd / meta)]

EOF
readonly ID=$1
readonly TYPE=$2

bash ../02_eq.sh $ID

case $TYPE in 
    md)  
        bash ../03_md_prod.sh $ID
        ;;

    smd)
        bash ../03_smd_prod.sh $ID
        ;;

    meta)
        echo "not implented yet"
        exit 0
        ;;
    *)
        echo "Invalid option: $TYPE"
        ;;
esac
