#!/bin/bash
set -eu
source argparser

[ -d $prefix ] && read -p "$prefix already exists. Do you want to remove $prefix?[enter]" && rm -rf $prefix 
mkdir $prefix

cd $prefix 
bash ../01_prepMD.sh $PDB $BT
for i in $(seq 1 $N); do
    bash ../eq2prod $i md
done
cd -
